# Generated by Django 3.2 on 2021-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=13)),
                ('message', models.TextField()),
                ('service', models.CharField(choices=[('GH', 'General Health'), ('CA', 'Cardiology'), ('DE', 'Dental'), ('NE', 'Neurology'), ('OR', 'Orthopaedics')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
