# Generated by Django 3.2.9 on 2021-12-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(to='website.TeamLead'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='website.service'),
        ),
    ]
