# Generated by Django 3.2.11 on 2022-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
