# Generated by Django 3.2.11 on 2022-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
