# Generated by Django 3.2.11 on 2022-03-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='available_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
