# Generated by Django 3.2.11 on 2022-03-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220301_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_hash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
