# Generated by Django 3.2.11 on 2022-02-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='d', max_length=200),
            preserve_default=False,
        ),
    ]
